setwd("/media/prasad/Edu/Stat 6021")
# Wednesday, September 17
install.packages("leaps")
library(leaps)
install.packages("MASS")
library(MASS)
#
# Multiple regression
#
# On each of 20 lakes, wilderness managers have
# data on the size of the fish catch (the response)
# the number of residents, and the size of the lake.
#
fish = read.csv("fish02.csv", header = TRUE)
#
plot(fish,pch=20,cex=.2)
#
fish.lm <- lm(catch~residents+size+season, data=fish)
#
# A summary of the values generated by lm:
#
summary(fish.lm)
#
# The "leaps" function will give the best model based
# on various criterion
fish.leaps <- leaps(x=fish[,2:4], y=fish[,1],
                names=names(fish)[2:4],method="r2")
fish.leaps
#
# This time we use adjusted R^2
fish.leaps <- leaps(x=fish[,2:4], y=fish[,1],
                    names=names(fish)[2:4],method="adjr2")
fish.leaps
#
# It also works for Mallow's C_p
fish.leaps <- leaps(x=fish[,2:4], y=fish[,1],
                    names=names(fish)[2:4],method="Cp")
fish.leaps
#
# The function "extractAIC" will compute the AIC
# for a given model
extractAIC(fish.lm, k=2)

# Changing k=log(n) gives the BIC:
extractAIC(fish.lm, k=log(20))

#
# "stepAIC" implements stepwise variable
# selection.
step <- stepAIC(fish.lm, direction="both", k=2)

# Changing k produces "stepBIC"
step <- stepAIC(fish.lm, direction="both", k=log(20))


#
# Practice data set
# 
steel = read.csv("steel.csv", header = TRUE)
plot(steel,pch=20,cex=.2)
steel.lm <- lm(tensile~units+width+temp+density, data=steel)
step <- stepAIC(steel.lm,direction = "both",k = 2)
step <- stepAIC(steel.lm,direction = "both",k = log(20))
