# Monday, September 15
#
# Multiple regression
#
# On each of 20 lakes, wilderness managers have
# data on the size of the fish catch (the response)
# the number of residents, and the size of the lake.
#
setwd("/media/prasad/Edu/Stat 6021/part8")
fish = read.csv("fish01.csv", header = TRUE)
#
# Start with a plot of the data
#
plot(fish,pch=20,cex=.2)
#
fish.lm <- lm(catch ~ residents+size, data=fish)
#
# A summary of the values generated by lm:
#
summary(fish.lm)
#
# It's interesting to see what we get from 
# using the individual variables
#
fish.lm <- lm(catch ~ residents+size, data=fish)
summary(fish.lm)
#
fish.lm <- lm(catch ~ size, data=fish)
summary(fish.lm)
#
# anova(fish.lm) gives a summary of the
# contribution of each variable in order
# with order of variable mattering
anova(fish.lm)
#
# New data set: used car sales data
#
cars = read.csv("usedcars.csv", header = TRUE)
#
# The "usedcars.csv" data set contains
# information about over 800 used car 
# sale prices.
#
plot(Price~Mileage,data=cars,pch=20,cex=.2)

lacrosse<-subset(cars, Model=="Lacrosse")
plot(Price~Mileage,data=lacrosse,pch=20,cex=.2)

# Activity:  Determine which quantitative 
# variables seem to contribute to explaining
# a used car price for your assigned car type
# from the following list:
#
# Cadillac Deville
# Chevrolet AVEO
# Chevrolet Cobalt
# Pontiac Vibe
# Saturn Ion
# Saab 9_5
# 