# Friday, September 5
#
# Simple linear regression
#
# Start by importing data set "brainhead.csv" that
# has 237 measurements of head size (cm^3) and brain
# weight (grams).  Also included are gender (1=m, 2=f)
# and age range (1=20-46, 2=46+)
#
setwd("/media/prasad/Edu/Stat 6021/part4")
bh = read.csv("brainhead .csv", header = TRUE)
#
plot(bh[,3:4],pch=20,cex=.2)
# We can fit a line to the data x = HeadSize and
# y = BrainWeight with the following:
#
brain.lm <- lm(BrainWeight ~ HeadSize, data=bh)
#
# A summary of the values generated by lm:
#
summary(brain.lm)
#
# The plot function provides a number of
# diagnostic plots
#
plot(brain.lm,pch=20,cex=.2,which=1:2)
#
# The "qreference" plot function 
# provides comparisons for qq-plots.
# Note: Requires the DAAG package
#
qreference(residuals(brain.lm),nrep=8,nrow=2)
