# Friday, September 12
#
# Multiple regression
#
# First, test out the derived matrix-based
# formula for simple linear regression
#
# Define the data
main <- rm(list=ls(all =T))
setwd("/media/prasad/Edu/Stat 6021/part7")
x = c(1,3,4) 
y = c(1,4,3)
test01 <- data.frame(x,y)
#
test01.lm <- lm(y ~ x, data=test01)
summary(test01.lm)
#
# On each of 20 lakes, wilderness managers have
# data on the size of the fish catch (the response)
# the number of residents, and the size of the lake.
#
fish = read.csv("fish01.csv", header = TRUE)
#
# Start with a plot of the data
#
plot(fish,pch=20,cex=.2)
#
fish.lm <- lm(catch ~ residents+size, data=fish)
#
# A summary of the values generated by lm:
#
summary(fish.lm)
#
# It's interesting to see what we get from 
# using the individual variables
#
fish.lm <- lm(catch ~ residents, data=fish)
summary(fish.lm)
#
fish.lm <- lm(catch ~ size, data=fish)
summary(fish.lm)


