setwd("/media/prasad/Edu/Stat 6021/part6")
# Wednesday, September 10
#
# Outlier detection, prediction and
# confidence intervals
#
## Prediction & confidence intervals
#
bh = read.csv("brainhead.csv", header = TRUE)
#
# A plot of the data
#
plot(BrainWeight~HeadSize, data=bh,pch=20,cex=.2)
# 
# Find the linear model
#
bh.lm <- lm(BrainWeight~HeadSize, data=bh)
#
# A summary of the values generated by lm:
#
summary(bh.lm)
#
# "abline" will include a regression line
# along with a scatter plot of the data
#
abline(bh.lm, col="red")
#
# One can use "predict" to give a predicted
# y-value for a given x-value, as well as 
# confidence or prediction intervals.
#
# Start with desired x-values, then predict:
newvalues = data.frame(HeadSize=c(3000,4000))
#
# Option "conf" gives confidence intervals
predict(bh.lm, newvalues, interval="conf")
#
# Option "predict" gives prediction intervals
predict(bh.lm, newvalues, interval="predict")

# The plot function provides a number of
# diagnostic plots, including the residual plot
#
# It is interesting to insert prediction and
# confidence bands on the scatterplot
abline(bh.lm, col="red")
# Define a sequence of x-values for predicting
x <- data.frame(HeadSize=(2500:5000))
# Define a sequence of prediction and confidence
# intervals for each x-value
confs <- predict(bh.lm, x, interval="conf")
preds <- predict(bh.lm, x, interval="predict")
#
# Now "connect the dots" with the prediction
# intervals in red and confidence intervals
# in blue
lines((2500:5000),confs[,2], type="l", col="blue")
lines((2500:5000),confs[,3], type="l", col="blue")
lines((2500:5000),preds[,2], type="l", col="red")
lines((2500:5000),preds[,3], type="l", col="red")
#
## Identifying outliers
#
# Start with a scatterplot
plot(BrainWeight~HeadSize, data=bh,pch=20,cex=.2)
#
# Compute and plot the Cook's distance
# for each observation
#
plot(bh.lm,pch=20,cex=.2,which=4)
#
# Plot the standardized residuals
# rstandard returns list of residuals
# divided by the residual standard
# error
bh.stdres = rstandard(bh.lm)
plot(bh$HeadSize,bh.stdres,pch=20,cex=.2)
#
# This will show leverage with Cook's D
#
plot(bh.lm,pch=20,cex=.2,which=6)
#
# We can directly compute and display
# leverage along with line marking
# "interesting" values
x.bar <- mean(bh$HeadSize)
sx <- sd(bh$HeadSize)
h <- (((bh$HeadSize-x.bar)/sx)^2)/236 + 1/237
#
plot(h,pch=20,cex=.2)
abline(h=(2/237),col="red")
#
## Activities
#
# 1. Create a data frame "bh1" that consists of
# rows 10,20,...230 of the bh data.
# 2. Generate a linear model for bh1, and
# use it to predict the brain weight for
# a head size of 4000.
# 3. Append the points (6000,1950) and
# (4500,100) to bh1.  (The other variables
# can be set equal to 1)
# 4. bh1 has outliers; find them, and do 
# diagnostics on them.






